### ISSUE TITLE
sbatch FileNotFoundError

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pysqa#153]
While trying to install and setup pyiron on a new machine we got following error when trying to submit a simple Lammps test job:

FileNotFoundError: [Errno 2] No such file or directory: 'sbatch'

When submitting the job directly logged into the cluster using sbatch run_queue.sh it works fine, also when manually starting python and submitting using subprocess.check_output(["sbatch", "run_queue.sh"]) no problems occur. I highly appreciate any ideas what could cause this.

Maybe @jan-janssen has a hint for me?

**Comment by jan-janssen** [comment]
I presume it is related to the environment. Are you running pyiron from the command line or from a Jupyter notebook? Depending on how the Jupyter installation is configured there might be differences between what you get when you call `!env` on jupyter vs. `env` on the command line. In the background pyiron is calling `sbatch` in a very similar way to what you describe: https://github.com/pyiron/pysqa/blob/main/pysqa/wrapper/slurm.py#L24 we get the `sbatch` command and then we call it in https://github.com/pyiron/pysqa/blob/72b8a2a0c0d9d8a68a6671742a717650274395e2/pysqa/utils/basic.py#L412

**Comment by Leimeroth** [comment]
Exporting the path to sbatch in the .bashrc on the cluster fixed it.  This was not necessary for any other installation on our system so I am still somewhat confused why the path seems to be messed up in this case.

**Comment by jan-janssen** [comment]
@Leimeroth I just had a similar issue - Can you check if https://github.com/pyiron/pysqa/pull/201 helps?
