### ISSUE TITLE
Compatible with PBS Professional scheduler?

### ISSUE THREAD

**Issue by hari-ushankar** [pyiron/pysqa#65]
Hi there,

This is not an issue really. 

I was wondering if it is possible to extend `pysqa` to submit jobs using PBS job scheduler.

I'm really happy with how `pysqa` nicely submits job in SLURM.

I have access to another cluster which uses [PBS Professional](https://www.altair.com/pdfs/pbsworks/PBSUserGuide19.2.3.pdf) to submit jobs.

It'd be really nice to run pyiron jobs over there as well. 

Is it possible to just add a jinja2 template for PBS and that's all there is to extend? Or is there something else that needs to be done?

A sample submission script looks like this:

```
#!/bin/bash
 
#PBS -l walltime=10:00:00,select=1:ncpus=1:mem=2gb
#PBS -N job_name
#PBS -A alloc-code
#PBS -m abe
#PBS -M your.name@ubc.ca
#PBS -o output.txt
#PBS -e error.txt
 
################################################################################
 
module load software_package_1
module load software_package_2
 
cd $PBS_O_WORKDIR
 
<executable commands here>
````

**Comment by jan-janssen** [comment]
We have a wrapper for the sun grid engine https://github.com/pyiron/pysqa/blob/master/pysqa/wrapper/sge.py which should be compatible in terms of the commands, but you might have to modify it to correctly parse the output of `qstat` and so on.

**Comment by hari-ushankar** [comment]
Ah I see, the commands look very similar to PBS Pro. I'll give it a shot.

So if I understood you correctly, I need a `pbs.py` file (which has all function definitions similar to `sge.py` above) and two files- `pbs.sh` and `queue.yaml`?

**Comment by jan-janssen** [comment]
You can start by just setting the queue type in queue.yaml to either SGE or TORQUE
 
```
queue_type: SGE 
```

only when there is an issue with the parsing then it is necessary to create your own parser `pbs.py`

Here are example configuration 
https://github.com/pyiron/pysqa/tree/master/tests/config/sge
https://github.com/pyiron/pysqa/tree/master/tests/config/torque

**Comment by hari-ushankar** [comment]
Super, this is very helpful.

You can close this issue, I'll re-open it or open another one if there are any more questions.

Thank you very much, @jan-janssen .
